### Server info

https://api.steampowered.com/ISteamWebAPIUtil/GetServerInfo/v1/

### Resolve vanity URL
https://api.steampowered.com/ISteamUser/ResolveVanityURL/v1/?key={{key}}&vanityurl={{vanityurl}}

### Get user info
https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key={{key}}&steamids={{steamid}}

### Get Games

https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key={{key}}&steamid={{steamid}}&include_appinfo=1&
    include_played_free_games=1&include_extended_appinfo=1

###

https://api.steampowered.com/ISteamUserOAuth/GetUserSummaries/v1/?key={{key}}

### Get app info
https://api.steampowered.com/IStoreService/GetAppInfo/v1/?key={{key}}&id=440

### Get apps
https://api.steampowered.com/IStoreService/GetAppList/v1/?key={{key}}

### Get info of single game

