name: backend

on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull latest from GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          pull: true
          tags: ghcr.io/wjdp/${{ env.IMAGE_NAME }}:latest
      - name: Build & push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/wjdp/${{ env.IMAGE_NAME }}:${{ env.GITHUB_REF_SLUG }},ghcr.io/wjdp/${{ env.IMAGE_NAME }}:latest
          cache-from: |
            type=registry,ref=ghcr.io/wjdp/${{ env.IMAGE_NAME }}:${{ env.GITHUB_REF_SLUG }}
            type=registry,ref=ghcr.io/wjdp/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          build-args: |
            VCS_REV=${{ env.GITHUB_REF_SLUG }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
